// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApEIy3JLBk8_n6AIKirl1nbnhX98Ouf2k',
    appId: '1:286718968181:web:c372c82b661bbb9901933c',
    messagingSenderId: '286718968181',
    projectId: 'taskmallow-app',
    authDomain: 'taskmallow-app.firebaseapp.com',
    databaseURL: 'https://taskmallow-app-default-rtdb.firebaseio.com',
    storageBucket: 'taskmallow-app.appspot.com',
    measurementId: 'G-3VRW7675H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZXGDZqPC4Uni18ot9Pr0vt7nJQB7EWXQ',
    appId: '1:286718968181:android:dfd92eb5de99546c01933c',
    messagingSenderId: '286718968181',
    projectId: 'taskmallow-app',
    databaseURL: 'https://taskmallow-app-default-rtdb.firebaseio.com',
    storageBucket: 'taskmallow-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNbyRw2K7IjbYzqFGlYVbjfi_6jDo0_-4',
    appId: '1:286718968181:ios:c8a439a740c1e0af01933c',
    messagingSenderId: '286718968181',
    projectId: 'taskmallow-app',
    databaseURL: 'https://taskmallow-app-default-rtdb.firebaseio.com',
    storageBucket: 'taskmallow-app.appspot.com',
    iosClientId: '286718968181-57kbi9opkiqd6l1f3eoja6pf5iap7fog.apps.googleusercontent.com',
    iosBundleId: 'com.taskmallow.taskmallow',
  );
}
